version: '3.4'

networks:
  my-network:
    driver: bridge

services:
  e-commerce:
    image: ${DOCKER_REGISTRY-}ecommerce
    container_name: ecommerce.api
    build:
      context: .
      dockerfile: E-commerce/Dockerfile
    ports: 
      - 5000:5000
      - 5001:5001
    networks:
      - my-network
    depends_on:
      - ecommerce.database

  ecommerce.database:
    image: postgres:latest
    container_name: ecommerce.database
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/e-commerce-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-network

  ecommerce.redis:
    image: redis:latest
    container_name: ecommerce.redis
    ports:
      - 6379:6379
    networks:
      - my-network

  ecommerce.rabbitmq:
    image:  rabbitmq:latest
    container_name: ecommerce.rabbitmq
    ports:
      - 5672:5672
    networks:
      - my-network

  
    
  